CREATE TABLE IF NOT EXISTS app_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL UNIQUE,
  lifecycle_state text NOT NULL DEFAULT 'active' CHECK (
    lifecycle_state IN ('active', 'deletion_requested', 'purging')
  ),
  deletion_requested_at timestamptz,
  next_session_number bigint NOT NULL DEFAULT 1 CHECK (
    next_session_number > 0
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT accounts_deletion_state_consistent CHECK (
    (lifecycle_state = 'active' AND deletion_requested_at IS NULL)
    OR
    (lifecycle_state IN ('deletion_requested', 'purging') AND deletion_requested_at IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS players (
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
  name_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES accounts(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS players_owner_name_key_idx
  ON players (owner_id, name_key)
  WHERE owner_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS players_owner_active_name_idx
  ON players (owner_id, lower(name))
  WHERE owner_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS players_active_name_idx
  ON players (lower(name))
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS poker_sessions (
  record_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id text NOT NULL,
  session_number bigint GENERATED BY DEFAULT AS IDENTITY,
  game_name text CONSTRAINT poker_sessions_game_name_length CHECK (
    game_name IS NULL OR char_length(game_name) BETWEEN 1 AND 80
  ),
  played_at timestamptz NOT NULL,
  ended_at timestamptz NOT NULL,
  ante bigint NOT NULL CHECK (ante > 0),
  starting_stack bigint NOT NULL CHECK (starting_stack >= 0),
  hands integer NOT NULL CHECK (hands > 0),
  blind_history jsonb,
  results jsonb NOT NULL CHECK (
    jsonb_typeof(results) = 'array'
    AND jsonb_array_length(results) BETWEEN 2 AND 10
  ),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS session_number bigint
  GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS game_name text;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS blind_history jsonb;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS owner_session_number bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'poker_sessions_game_name_length'
      AND conrelid = 'public.poker_sessions'::regclass
  ) THEN
    ALTER TABLE poker_sessions
      ADD CONSTRAINT poker_sessions_game_name_length
      CHECK (
        game_name IS NULL OR char_length(game_name) BETWEEN 1 AND 80
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'poker_sessions_owner_number_pair'
      AND conrelid = 'public.poker_sessions'::regclass
  ) THEN
    ALTER TABLE poker_sessions
      ADD CONSTRAINT poker_sessions_owner_number_pair
      CHECK (
        (owner_id IS NULL AND owner_session_number IS NULL)
        OR
        (owner_id IS NOT NULL AND owner_session_number IS NOT NULL)
      );
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS poker_sessions_legacy_id_idx
  ON poker_sessions (id)
  WHERE owner_id IS NULL;

CREATE INDEX IF NOT EXISTS poker_sessions_played_at_idx
  ON poker_sessions (played_at DESC);

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS discarded_at timestamptz;

CREATE INDEX IF NOT EXISTS poker_sessions_active_played_at_idx
  ON poker_sessions (played_at DESC, created_at DESC)
  WHERE discarded_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS poker_sessions_owner_number_idx
  ON poker_sessions (owner_id, owner_session_number)
  WHERE owner_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS poker_sessions_owner_client_id_idx
  ON poker_sessions (owner_id, id)
  WHERE owner_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS poker_sessions_owner_played_at_idx
  ON poker_sessions (owner_id, played_at DESC, created_at DESC)
  WHERE owner_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS migration_mapping (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_kind text NOT NULL CHECK (source_kind IN ('player', 'session')),
  source_id text NOT NULL,
  target_owner_id uuid REFERENCES accounts(id) ON DELETE CASCADE,
  target_id text,
  review_status text NOT NULL DEFAULT 'pending' CHECK (
    review_status IN ('pending', 'approved', 'quarantined', 'migrated')
  ),
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (
    jsonb_typeof(provenance) = 'object'
  ),
  reviewed_at timestamptz,
  migrated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS migration_mapping_owner_source_idx
  ON migration_mapping (source_kind, source_id, target_owner_id)
  WHERE target_owner_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS audit_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  actor_auth_user_id uuid NOT NULL,
  action text NOT NULL CHECK (char_length(action) BETWEEN 1 AND 100),
  target_kind text NOT NULL CHECK (char_length(target_kind) BETWEEN 1 AND 60),
  target_id text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (
    jsonb_typeof(details) = 'object'
  ),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_events_owner_created_at_idx
  ON audit_events (owner_id, created_at DESC);

INSERT INTO players (name, name_key)
SELECT DISTINCT ON (name_key) name, name_key
FROM (
  SELECT
    btrim(result->>'name') AS name,
    lower(regexp_replace(btrim(result->>'name'), '\s+', ' ', 'g')) AS name_key
  FROM poker_sessions
  CROSS JOIN LATERAL jsonb_array_elements(results) AS result
  WHERE nullif(btrim(result->>'name'), '') IS NOT NULL
) AS existing_players
ORDER BY name_key, name
ON CONFLICT DO NOTHING;

UPDATE poker_sessions AS session
SET results = mapped.results
FROM (
  SELECT
    poker_sessions.record_id,
    jsonb_agg(
      result || jsonb_build_object('playerId', players.id)
      ORDER BY result_position
    ) AS results
  FROM poker_sessions
  CROSS JOIN LATERAL jsonb_array_elements(results)
    WITH ORDINALITY AS session_result(result, result_position)
  JOIN players
    ON players.name_key = lower(
      regexp_replace(btrim(result->>'name'), '\s+', ' ', 'g')
    )
  GROUP BY poker_sessions.record_id
) AS mapped
WHERE session.record_id = mapped.record_id
  AND session.results IS DISTINCT FROM mapped.results;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'players_owner_id_id_unique'
      AND conrelid = 'public.players'::regclass
  ) THEN
    ALTER TABLE players
      ADD CONSTRAINT players_owner_id_id_unique UNIQUE (owner_id, id);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'poker_sessions_owner_record_unique'
      AND conrelid = 'public.poker_sessions'::regclass
  ) THEN
    ALTER TABLE poker_sessions
      ADD CONSTRAINT poker_sessions_owner_record_unique
      UNIQUE (owner_id, record_id);
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS session_results (
  owner_id uuid NOT NULL,
  session_record_id uuid NOT NULL,
  player_id text NOT NULL,
  position smallint NOT NULL CHECK (position BETWEEN 1 AND 10),
  player_name text NOT NULL CHECK (char_length(player_name) BETWEEN 1 AND 80),
  invested bigint NOT NULL CHECK (invested >= 0),
  ending_stack bigint NOT NULL CHECK (ending_stack >= 0),
  net bigint GENERATED ALWAYS AS (ending_stack - invested) STORED,
  accounting_status text NOT NULL CHECK (
    accounting_status IN ('verified', 'legacy_verified', 'unverified')
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_id, session_record_id, player_id),
  UNIQUE (owner_id, session_record_id, position),
  FOREIGN KEY (owner_id, session_record_id)
    REFERENCES poker_sessions (owner_id, record_id) ON DELETE CASCADE,
  FOREIGN KEY (owner_id, player_id)
    REFERENCES players (owner_id, id)
    ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS buy_in_events (
  owner_id uuid NOT NULL,
  session_record_id uuid NOT NULL,
  player_id text NOT NULL,
  sequence smallint NOT NULL CHECK (sequence BETWEEN 1 AND 64),
  kind text NOT NULL CHECK (kind IN ('initial', 'rebuy')),
  amount bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_id, session_record_id, player_id, sequence),
  FOREIGN KEY (owner_id, session_record_id, player_id)
    REFERENCES session_results (owner_id, session_record_id, player_id)
    ON DELETE CASCADE,
  CONSTRAINT buy_in_events_kind_sequence CHECK (
    (sequence = 1 AND kind = 'initial' AND amount >= 0)
    OR
    (sequence > 1 AND kind = 'rebuy' AND amount > 0)
  )
);

CREATE INDEX IF NOT EXISTS session_results_owner_player_idx
  ON session_results (owner_id, player_id, session_record_id);

CREATE INDEX IF NOT EXISTS buy_in_events_owner_session_idx
  ON buy_in_events (owner_id, session_record_id, player_id, sequence);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM poker_sessions AS session
    CROSS JOIN LATERAL jsonb_array_elements(session.results) AS result(value)
    WHERE session.owner_id IS NOT NULL
      AND (
        nullif(result.value->>'playerId', '') IS NULL
        OR NOT EXISTS (
          SELECT 1
          FROM players AS player
          WHERE player.owner_id = session.owner_id
            AND player.id = result.value->>'playerId'
        )
        OR (
          result.value ? 'buyIns'
          AND CASE
            WHEN jsonb_typeof(result.value->'buyIns') <> 'array' THEN true
            ELSE jsonb_array_length(result.value->'buyIns') = 0
          END
        )
      )
  ) THEN
    RAISE EXCEPTION 'Owned session results have invalid player or buy-in references';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM (
      SELECT
        session.record_id,
        count(*) AS result_count,
        count(DISTINCT result.value->>'playerId') AS player_count,
        sum((result.value->>'end')::bigint) AS total_ending,
        sum((result.value->>'net')::bigint) AS total_net,
        sum(
          CASE
            WHEN result.value ? 'buyIns' THEN (
              SELECT sum(amount.value::bigint)
              FROM jsonb_array_elements_text(result.value->'buyIns')
                AS amount(value)
            )
            ELSE session.starting_stack
          END
        ) AS total_invested,
        bool_and(
          (result.value->>'end')::bigint - (result.value->>'net')::bigint
          = CASE
            WHEN result.value ? 'buyIns' THEN (
              SELECT sum(amount.value::bigint)
              FROM jsonb_array_elements_text(result.value->'buyIns')
                AS amount(value)
            )
            ELSE session.starting_stack
          END
        ) AS individual_balanced
      FROM poker_sessions AS session
      CROSS JOIN LATERAL jsonb_array_elements(session.results) AS result(value)
      WHERE session.owner_id IS NOT NULL
      GROUP BY session.record_id
    ) AS accounting
    WHERE accounting.result_count <> accounting.player_count
      OR NOT accounting.individual_balanced
      OR accounting.total_net <> 0
      OR accounting.total_ending <> accounting.total_invested
  ) THEN
    RAISE EXCEPTION 'Owned session accounting does not reconcile';
  END IF;
END
$$;

INSERT INTO session_results (
  owner_id,
  session_record_id,
  player_id,
  position,
  player_name,
  invested,
  ending_stack,
  accounting_status
)
SELECT
  session.owner_id,
  session.record_id,
  result.value->>'playerId',
  result.position,
  result.value->>'name',
  CASE
    WHEN result.value ? 'buyIns' THEN (
      SELECT sum(amount.value::bigint)
      FROM jsonb_array_elements_text(result.value->'buyIns') AS amount(value)
    )
    ELSE session.starting_stack
  END,
  (result.value->>'end')::bigint,
  'legacy_verified'
FROM poker_sessions AS session
CROSS JOIN LATERAL jsonb_array_elements(session.results)
  WITH ORDINALITY AS result(value, position)
WHERE session.owner_id IS NOT NULL
ON CONFLICT (owner_id, session_record_id, player_id) DO NOTHING;

INSERT INTO buy_in_events (
  owner_id,
  session_record_id,
  player_id,
  sequence,
  kind,
  amount
)
SELECT
  session.owner_id,
  session.record_id,
  result.value->>'playerId',
  buy_in.position,
  CASE WHEN buy_in.position = 1 THEN 'initial' ELSE 'rebuy' END,
  buy_in.value::bigint
FROM poker_sessions AS session
CROSS JOIN LATERAL jsonb_array_elements(session.results) AS result(value)
CROSS JOIN LATERAL jsonb_array_elements_text(
  CASE
    WHEN result.value ? 'buyIns' THEN result.value->'buyIns'
    ELSE jsonb_build_array(session.starting_stack)
  END
) WITH ORDINALITY AS buy_in(value, position)
WHERE session.owner_id IS NOT NULL
ON CONFLICT (owner_id, session_record_id, player_id, sequence) DO NOTHING;

CREATE OR REPLACE FUNCTION public.current_app_auth_user_id()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT CASE
    WHEN current_setting('app.current_auth_user_id', true)
      ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    THEN current_setting('app.current_auth_user_id', true)::uuid
    ELSE NULL
  END
$$;

CREATE OR REPLACE FUNCTION public.current_app_account_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT account.id
  FROM public.accounts AS account
  WHERE account.auth_user_id = public.current_app_auth_user_id()
$$;

REVOKE ALL ON FUNCTION public.current_app_auth_user_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.current_app_account_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_app_auth_user_id() TO menoka_app;
GRANT EXECUTE ON FUNCTION public.current_app_account_id() TO menoka_app;

ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE poker_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE buy_in_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE migration_mapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS accounts_runtime_isolation ON accounts;
CREATE POLICY accounts_runtime_isolation ON accounts
  FOR ALL TO menoka_app
  USING (auth_user_id = public.current_app_auth_user_id())
  WITH CHECK (auth_user_id = public.current_app_auth_user_id());

DROP POLICY IF EXISTS players_runtime_isolation ON players;
CREATE POLICY players_runtime_isolation ON players
  FOR ALL TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS poker_sessions_runtime_isolation ON poker_sessions;
CREATE POLICY poker_sessions_runtime_isolation ON poker_sessions
  FOR ALL TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS session_results_runtime_isolation ON session_results;
CREATE POLICY session_results_runtime_isolation ON session_results
  FOR ALL TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS buy_in_events_runtime_isolation ON buy_in_events;
CREATE POLICY buy_in_events_runtime_isolation ON buy_in_events
  FOR ALL TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS migration_mapping_runtime_isolation ON migration_mapping;
CREATE POLICY migration_mapping_runtime_isolation ON migration_mapping
  FOR SELECT TO menoka_app
  USING (target_owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS audit_events_runtime_isolation ON audit_events;
CREATE POLICY audit_events_runtime_isolation ON audit_events
  FOR SELECT TO menoka_app
  USING (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS audit_events_runtime_insert ON audit_events;
CREATE POLICY audit_events_runtime_insert ON audit_events
  FOR INSERT TO menoka_app
  WITH CHECK (
    owner_id = public.current_app_account_id()
    AND actor_auth_user_id = public.current_app_auth_user_id()
  );

REVOKE ALL ON SCHEMA public FROM menoka_app;
GRANT USAGE ON SCHEMA public TO menoka_app;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM menoka_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM menoka_app;
GRANT SELECT, INSERT, UPDATE ON accounts TO menoka_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON players TO menoka_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON poker_sessions TO menoka_app;
GRANT SELECT, INSERT ON session_results TO menoka_app;
GRANT SELECT, INSERT ON buy_in_events TO menoka_app;
GRANT SELECT, INSERT ON audit_events TO menoka_app;

-- The runtime role may only request deletion or cancel it inside the
-- 30-day grace period. Purging is reserved for the separate purge job.
CREATE OR REPLACE FUNCTION public.guard_account_lifecycle()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF current_user <> 'menoka_app' THEN
    RETURN NEW;
  END IF;

  IF NEW.lifecycle_state = OLD.lifecycle_state THEN
    IF NEW.deletion_requested_at IS DISTINCT FROM OLD.deletion_requested_at THEN
      RAISE EXCEPTION 'deletion time cannot change without a lifecycle change';
    END IF;
    RETURN NEW;
  END IF;

  IF OLD.lifecycle_state = 'active' AND NEW.lifecycle_state = 'deletion_requested' THEN
    NEW.deletion_requested_at := now();
    RETURN NEW;
  END IF;

  IF OLD.lifecycle_state = 'deletion_requested' AND NEW.lifecycle_state = 'active' THEN
    IF OLD.deletion_requested_at <= now() - interval '30 days' THEN
      RAISE EXCEPTION 'the recovery period has ended';
    END IF;
    NEW.deletion_requested_at := NULL;
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'account lifecycle change from % to % is not allowed',
    OLD.lifecycle_state, NEW.lifecycle_state;
END
$$;

DROP TRIGGER IF EXISTS accounts_guard_lifecycle ON accounts;
CREATE TRIGGER accounts_guard_lifecycle
  BEFORE UPDATE ON accounts
  FOR EACH ROW
  EXECUTE FUNCTION public.guard_account_lifecycle();
GRANT USAGE, SELECT ON SEQUENCE poker_sessions_session_number_seq
  TO menoka_app;

-- Account purge job. Requires the menoka_purge role (see migrations/README.md).
-- One row per purged account. It deliberately has no foreign key so it
-- outlives the account; the Auth user ID is cleared once the purge is done.
CREATE TABLE IF NOT EXISTS account_purges (
  account_id uuid PRIMARY KEY,
  auth_user_id uuid,
  deletion_requested_at timestamptz NOT NULL,
  claimed_at timestamptz NOT NULL DEFAULT now(),
  identity_deleted_at timestamptz,
  data_deleted_at timestamptz,
  completed_at timestamptz,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  last_error text CHECK (char_length(last_error) <= 500),
  last_attempt_at timestamptz,
  CONSTRAINT account_purges_completion_consistent CHECK (
    completed_at IS NULL
    OR (identity_deleted_at IS NOT NULL AND data_deleted_at IS NOT NULL AND auth_user_id IS NULL)
  )
);

ALTER TABLE account_purges ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON account_purges FROM PUBLIC;

-- Moves every account past its 30-day grace period to purging and returns
-- all unfinished purges, including ones a previous run could not finish.
CREATE OR REPLACE FUNCTION public.purge_claim_due_accounts(max_accounts integer)
RETURNS TABLE (account_id uuid, auth_user_id uuid, attempts integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  WITH due AS (
    UPDATE accounts AS account
    SET lifecycle_state = 'purging', updated_at = now()
    WHERE account.lifecycle_state = 'deletion_requested'
      AND account.deletion_requested_at <= now() - interval '30 days'
    RETURNING account.id, account.auth_user_id, account.deletion_requested_at
  )
  INSERT INTO account_purges (account_id, auth_user_id, deletion_requested_at)
  SELECT due.id, due.auth_user_id, due.deletion_requested_at FROM due
  ON CONFLICT ON CONSTRAINT account_purges_pkey DO NOTHING;

  RETURN QUERY
  SELECT purge.account_id, purge.auth_user_id, purge.attempts
  FROM account_purges AS purge
  WHERE purge.completed_at IS NULL
  ORDER BY purge.claimed_at
  LIMIT greatest(1, least(max_accounts, 100));
END
$$;

-- True while the Neon Auth user still exists, so the job can confirm a
-- deletion without relying on the provider's response code.
CREATE OR REPLACE FUNCTION public.purge_auth_identity_exists(target_auth_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM neon_auth."user" WHERE id = target_auth_user_id
  )
$$;

CREATE OR REPLACE FUNCTION public.purge_record_identity_deleted(target_account_id uuid)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  UPDATE account_purges
  SET identity_deleted_at = coalesce(identity_deleted_at, now())
  WHERE account_id = target_account_id AND completed_at IS NULL
$$;

-- Deletes the account and, through ON DELETE CASCADE, every row it owns.
-- Only accounts already claimed for purging whose identity is gone qualify.
CREATE OR REPLACE FUNCTION public.purge_delete_account_data(target_account_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  purge account_purges%ROWTYPE;
BEGIN
  SELECT * INTO purge FROM account_purges
  WHERE account_id = target_account_id AND completed_at IS NULL
  FOR UPDATE;
  IF NOT FOUND OR purge.identity_deleted_at IS NULL THEN
    RETURN false;
  END IF;

  DELETE FROM accounts
  WHERE id = target_account_id AND lifecycle_state = 'purging';

  UPDATE account_purges
  SET data_deleted_at = now(),
      completed_at = now(),
      auth_user_id = NULL,
      last_error = NULL,
      last_attempt_at = now(),
      attempts = attempts + 1
  WHERE account_id = target_account_id;
  RETURN true;
END
$$;

CREATE OR REPLACE FUNCTION public.purge_record_failure(target_account_id uuid, failure text)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  UPDATE account_purges
  SET attempts = attempts + 1,
      last_error = left(failure, 500),
      last_attempt_at = now()
  WHERE account_id = target_account_id AND completed_at IS NULL
$$;

REVOKE ALL ON FUNCTION public.purge_claim_due_accounts(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.purge_auth_identity_exists(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.purge_record_identity_deleted(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.purge_delete_account_data(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.purge_record_failure(uuid, text) FROM PUBLIC;

GRANT USAGE ON SCHEMA public TO menoka_purge;
GRANT EXECUTE ON FUNCTION public.purge_claim_due_accounts(integer) TO menoka_purge;
GRANT EXECUTE ON FUNCTION public.purge_auth_identity_exists(uuid) TO menoka_purge;
GRANT EXECUTE ON FUNCTION public.purge_record_identity_deleted(uuid) TO menoka_purge;
GRANT EXECUTE ON FUNCTION public.purge_delete_account_data(uuid) TO menoka_purge;
GRANT EXECUTE ON FUNCTION public.purge_record_failure(uuid, text) TO menoka_purge;

-- Copies reviewed legacy games into one host's private ledger, after that host
-- has signed in once. Used at cutover for Rajarshi and later for hosts whose
-- games stay unowned until they sign in. Owner-only: the runtime roles cannot
-- execute it. Source rows stay unowned and untouched; the copies get
-- owner-local players, local game numbers, normalized results and buy-ins,
-- and provenance rows in migration_mapping. Rerunning it for the same games
-- changes nothing and returns 0.
CREATE OR REPLACE FUNCTION public.claim_reviewed_history(
  p_target_account uuid,
  p_session_numbers bigint[],
  p_friend_names text[],
  p_decision text
) RETURNS integer
LANGUAGE plpgsql
SET search_path = public, pg_temp
AS $$
DECLARE
  v_expected integer := cardinality(p_session_numbers);
  v_already integer;
  v_claimed integer;
  v_source_results integer;
BEGIN
  IF p_decision IS NULL OR btrim(p_decision) = '' THEN
    RAISE EXCEPTION 'Name the recorded ownership decision';
  END IF;

  IF v_expected IS NULL OR v_expected = 0 THEN
    RAISE EXCEPTION 'List at least one legacy game number';
  END IF;

  IF (SELECT count(DISTINCT n) FROM unnest(p_session_numbers) AS n) <> v_expected THEN
    RAISE EXCEPTION 'Legacy game numbers must not repeat';
  END IF;

  PERFORM 1
  FROM accounts
  WHERE id = p_target_account AND lifecycle_state = 'active'
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Target account is missing or inactive';
  END IF;

  IF (
    SELECT count(*)
    FROM poker_sessions
    WHERE owner_id IS NULL AND session_number = ANY (p_session_numbers)
  ) <> v_expected THEN
    RAISE EXCEPTION 'Expected % unowned legacy games, found a different set', v_expected;
  END IF;

  SELECT count(*) INTO v_already
  FROM poker_sessions AS source
  JOIN migration_mapping AS mapping
    ON mapping.source_kind = 'session'
   AND mapping.source_id = source.record_id::text
   AND mapping.target_owner_id = p_target_account
   AND mapping.review_status = 'migrated'
  WHERE source.owner_id IS NULL
    AND source.session_number = ANY (p_session_numbers);

  IF v_already = v_expected THEN
    RETURN 0;
  ELSIF v_already > 0 THEN
    RAISE EXCEPTION 'Only % of % games were claimed before; review before retrying', v_already, v_expected;
  END IF;

  -- Every participant must be on the reviewed friend list.
  IF EXISTS (
    SELECT 1
    FROM poker_sessions AS source
    CROSS JOIN LATERAL jsonb_array_elements(source.results) AS result(value)
    LEFT JOIN players AS legacy
      ON legacy.owner_id IS NULL
     AND legacy.id = result.value->>'playerId'
    WHERE source.owner_id IS NULL
      AND source.session_number = ANY (p_session_numbers)
      AND (
        legacy.id IS NULL
        OR legacy.name_key NOT IN (
          SELECT lower(regexp_replace(btrim(friend), '\s+', ' ', 'g'))
          FROM unnest(p_friend_names) AS friend
        )
      )
  ) THEN
    RAISE EXCEPTION 'A player in these games is missing or not on the friend list';
  END IF;

  INSERT INTO players (owner_id, name, name_key)
  SELECT
    p_target_account,
    btrim(friend),
    lower(regexp_replace(btrim(friend), '\s+', ' ', 'g'))
  FROM unnest(p_friend_names) AS friend
  ON CONFLICT (owner_id, name_key) WHERE owner_id IS NOT NULL DO NOTHING;

  INSERT INTO migration_mapping (
    source_kind, source_id, target_owner_id, target_id,
    review_status, provenance, reviewed_at, migrated_at
  )
  SELECT DISTINCT ON (legacy.id)
    'player',
    legacy.id,
    p_target_account,
    destination.id,
    'migrated',
    jsonb_build_object(
      'decision', p_decision,
      'manifest', 'docs/HISTORICAL-OWNERSHIP.md'
    ),
    now(),
    now()
  FROM poker_sessions AS source
  CROSS JOIN LATERAL jsonb_array_elements(source.results) AS result(value)
  JOIN players AS legacy
    ON legacy.owner_id IS NULL
   AND legacy.id = result.value->>'playerId'
  JOIN players AS destination
    ON destination.owner_id = p_target_account
   AND destination.name_key = legacy.name_key
  WHERE source.owner_id IS NULL
    AND source.session_number = ANY (p_session_numbers)
  ON CONFLICT (source_kind, source_id, target_owner_id)
    WHERE target_owner_id IS NOT NULL
  DO NOTHING;

  -- A second claim in the same transaction must not trip over the first.
  DROP TABLE IF EXISTS pg_temp.claim_session_copy;
  CREATE TEMP TABLE claim_session_copy ON COMMIT DROP AS
  SELECT
    source.record_id AS source_record_id,
    gen_random_uuid() AS target_record_id,
    source.session_number AS source_number,
    account.next_session_number - 1 + row_number() OVER (
      ORDER BY source.played_at, source.created_at, source.record_id
    ) AS local_number
  FROM poker_sessions AS source
  CROSS JOIN accounts AS account
  WHERE account.id = p_target_account
    AND source.owner_id IS NULL
    AND source.session_number = ANY (p_session_numbers);

  INSERT INTO poker_sessions (
    record_id, owner_id, owner_session_number, id, game_name, played_at,
    ended_at, ante, starting_stack, hands, blind_history, results, discarded_at
  )
  SELECT
    copy.target_record_id,
    p_target_account,
    copy.local_number,
    source.id,
    source.game_name,
    source.played_at,
    source.ended_at,
    source.ante,
    source.starting_stack,
    source.hands,
    source.blind_history,
    (
      SELECT jsonb_agg(
        result.value || jsonb_build_object(
          'playerId', destination.id,
          'name', destination.name
        )
        ORDER BY result.position
      )
      FROM jsonb_array_elements(source.results)
        WITH ORDINALITY AS result(value, position)
      JOIN migration_mapping AS mapping
        ON mapping.source_kind = 'player'
       AND mapping.source_id = result.value->>'playerId'
       AND mapping.target_owner_id = p_target_account
      JOIN players AS destination
        ON destination.owner_id = p_target_account
       AND destination.id = mapping.target_id
    ),
    source.discarded_at
  FROM claim_session_copy AS copy
  JOIN poker_sessions AS source ON source.record_id = copy.source_record_id;

  INSERT INTO session_results (
    owner_id, session_record_id, player_id, position, player_name,
    invested, ending_stack, accounting_status
  )
  SELECT
    p_target_account,
    copy.target_record_id,
    result.value->>'playerId',
    result.position,
    result.value->>'name',
    CASE
      WHEN result.value ? 'buyIns' THEN (
        SELECT sum(amount.value::bigint)
        FROM jsonb_array_elements_text(result.value->'buyIns') AS amount(value)
      )
      ELSE session.starting_stack
    END,
    (result.value->>'end')::bigint,
    'legacy_verified'
  FROM claim_session_copy AS copy
  JOIN poker_sessions AS session ON session.record_id = copy.target_record_id
  CROSS JOIN LATERAL jsonb_array_elements(session.results)
    WITH ORDINALITY AS result(value, position);

  INSERT INTO buy_in_events (
    owner_id, session_record_id, player_id, sequence, kind, amount
  )
  SELECT
    p_target_account,
    copy.target_record_id,
    result.value->>'playerId',
    buy_in.position,
    CASE WHEN buy_in.position = 1 THEN 'initial' ELSE 'rebuy' END,
    buy_in.value::bigint
  FROM claim_session_copy AS copy
  JOIN poker_sessions AS session ON session.record_id = copy.target_record_id
  CROSS JOIN LATERAL jsonb_array_elements(session.results) AS result(value)
  CROSS JOIN LATERAL jsonb_array_elements_text(
    CASE
      WHEN result.value ? 'buyIns' THEN result.value->'buyIns'
      ELSE jsonb_build_array(session.starting_stack)
    END
  ) WITH ORDINALITY AS buy_in(value, position);

  INSERT INTO migration_mapping (
    source_kind, source_id, target_owner_id, target_id,
    review_status, provenance, reviewed_at, migrated_at
  )
  SELECT
    'session',
    copy.source_record_id::text,
    p_target_account,
    copy.target_record_id::text,
    'migrated',
    jsonb_build_object(
      'decision', p_decision,
      'manifest', 'docs/HISTORICAL-OWNERSHIP.md',
      'sourceSessionNumber', copy.source_number
    ),
    now(),
    now()
  FROM claim_session_copy AS copy;

  UPDATE accounts
  SET
    next_session_number = next_session_number + v_expected,
    updated_at = now()
  WHERE id = p_target_account;

  -- Reconcile the copies against their sources.
  SELECT count(*) INTO v_claimed FROM claim_session_copy;

  SELECT count(*) INTO v_source_results
  FROM claim_session_copy AS copy
  JOIN poker_sessions AS source ON source.record_id = copy.source_record_id
  CROSS JOIN LATERAL jsonb_array_elements(source.results);

  IF v_claimed <> v_expected THEN
    RAISE EXCEPTION 'Claimed % games instead of %', v_claimed, v_expected;
  END IF;

  IF (
    SELECT count(*)
    FROM claim_session_copy AS copy
    JOIN session_results AS result
      ON result.owner_id = p_target_account
     AND result.session_record_id = copy.target_record_id
  ) <> v_source_results THEN
    RAISE EXCEPTION 'Claimed results do not match the source results';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM claim_session_copy AS copy
    JOIN poker_sessions AS source ON source.record_id = copy.source_record_id
    JOIN poker_sessions AS target ON target.record_id = copy.target_record_id
    CROSS JOIN LATERAL (
      SELECT
        (SELECT sum(r.net) FROM session_results AS r
          WHERE r.owner_id = p_target_account
            AND r.session_record_id = copy.target_record_id) AS target_net,
        (SELECT sum(r.ending_stack) FROM session_results AS r
          WHERE r.owner_id = p_target_account
            AND r.session_record_id = copy.target_record_id) AS target_ending,
        (SELECT sum(r.invested) FROM session_results AS r
          WHERE r.owner_id = p_target_account
            AND r.session_record_id = copy.target_record_id) AS target_invested,
        (SELECT coalesce(bool_and(
            r.net = (source_result.value->>'net')::bigint
            AND r.ending_stack = (source_result.value->>'end')::bigint
          ), false)
          FROM jsonb_array_elements(source.results)
            WITH ORDINALITY AS source_result(value, position)
          JOIN session_results AS r
            ON r.owner_id = p_target_account
           AND r.session_record_id = copy.target_record_id
           AND r.position = source_result.position) AS results_match,
        (SELECT sum(e.amount) FROM buy_in_events AS e
          WHERE e.owner_id = p_target_account
            AND e.session_record_id = copy.target_record_id) AS target_buy_ins
    ) AS totals
    WHERE totals.target_net <> 0
       OR totals.target_ending <> totals.target_invested
       OR totals.target_buy_ins <> totals.target_invested
       OR NOT totals.results_match
       OR target.discarded_at IS DISTINCT FROM source.discarded_at
  ) THEN
    RAISE EXCEPTION 'Claimed game accounting does not reconcile with its source';
  END IF;

  RETURN v_claimed;
END
$$;

REVOKE ALL ON FUNCTION public.claim_reviewed_history(uuid, bigint[], text[], text)
  FROM PUBLIC;

-- Live standings players open through a share link while a game is played.
-- One row per host: sharing again replaces the link. Only the SHA-256 hash of
-- the link's token is stored. The row holds the standings the server derived
-- from the host's last update and stops being readable 12 hours after it.
CREATE TABLE IF NOT EXISTS live_views (
  owner_id uuid PRIMARY KEY REFERENCES accounts(id) ON DELETE CASCADE,
  token_hash bytea NOT NULL UNIQUE CHECK (octet_length(token_hash) = 32),
  snapshot jsonb NOT NULL CHECK (
    jsonb_typeof(snapshot) = 'object' AND pg_column_size(snapshot) < 16384
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT now() + interval '12 hours',
  CONSTRAINT live_views_expiry_bounded CHECK (
    expires_at <= updated_at + interval '12 hours'
  )
);

ALTER TABLE live_views ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS live_views_runtime_isolation ON live_views;
CREATE POLICY live_views_runtime_isolation ON live_views
  FOR ALL
  TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

GRANT SELECT, INSERT, UPDATE, DELETE ON live_views TO menoka_app;

-- The public read behind a share link. It runs without a signed-in host, so
-- it bypasses row security and returns only the derived standings and their time,
-- and nothing once the link has expired or the host's account is locked.
CREATE OR REPLACE FUNCTION public.read_live_view(p_token_hash bytea)
RETURNS TABLE (snapshot jsonb, updated_at timestamptz)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT live.snapshot, live.updated_at
  FROM public.live_views AS live
  JOIN public.accounts AS account ON account.id = live.owner_id
  WHERE live.token_hash = p_token_hash
    AND live.expires_at > now()
    AND account.lifecycle_state = 'active'
$$;

REVOKE ALL ON FUNCTION public.read_live_view(bytea) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.read_live_view(bytea) TO menoka_app;


-- Friend network step 1: identity basics. Every account gets a user code that
-- other people will search for to send a friend request, and an optional
-- display name the person chooses. Every player profile gets its own code,
-- which a host can share with a player who hasn't signed up yet. Codes are
-- identifiers, not secrets: linking a login to a player always needs the
-- host's approval (a later step), so a known code grants nothing.

-- Eight characters from an alphabet without 0/O or 1/I/L. The bytes come from
-- gen_random_uuid(), which uses the server's strong random source; bytes 6 and
-- 8 carry the UUID version and variant, so only fully random bytes are used.
-- Taking each byte modulo 31 favours the first eight characters very slightly
-- (9/256 against 8/256), which is harmless for identifiers.
CREATE OR REPLACE FUNCTION public.new_identity_code()
RETURNS text
LANGUAGE sql
VOLATILE
SET search_path = pg_catalog
AS $$
  SELECT string_agg(
    substr(
      '23456789ABCDEFGHJKMNPQRSTUVWXYZ',
      get_byte(source.random_bytes, byte_position) % 31 + 1,
      1
    ),
    ''
    ORDER BY byte_position
  )
  FROM (SELECT uuid_send(gen_random_uuid()) AS random_bytes) AS source,
    unnest(ARRAY[0, 1, 2, 3, 4, 5, 10, 11]) AS byte_position
$$;

REVOKE ALL ON FUNCTION public.new_identity_code() FROM PUBLIC;
-- The runtime role evaluates the column defaults below when it provisions an
-- account or adds a player, and calls the function when a person replaces
-- their code.
GRANT EXECUTE ON FUNCTION public.new_identity_code() TO menoka_app;

-- A volatile default is evaluated per row while the column is added, so every
-- existing account and player gets its own code.
ALTER TABLE accounts
  ADD COLUMN IF NOT EXISTS user_code text DEFAULT public.new_identity_code();
ALTER TABLE accounts ALTER COLUMN user_code SET NOT NULL;
ALTER TABLE accounts DROP CONSTRAINT IF EXISTS accounts_user_code_format;
ALTER TABLE accounts ADD CONSTRAINT accounts_user_code_format
  CHECK (user_code ~ '^[2-9A-HJKMNP-Z]{8}$');
CREATE UNIQUE INDEX IF NOT EXISTS accounts_user_code_idx
  ON accounts (user_code);

ALTER TABLE accounts ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE accounts DROP CONSTRAINT IF EXISTS accounts_display_name_valid;
ALTER TABLE accounts ADD CONSTRAINT accounts_display_name_valid CHECK (
  display_name IS NULL
  OR (
    char_length(display_name) BETWEEN 1 AND 40
    AND display_name = btrim(display_name)
  )
);

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS player_code text DEFAULT public.new_identity_code();
ALTER TABLE players ALTER COLUMN player_code SET NOT NULL;
ALTER TABLE players DROP CONSTRAINT IF EXISTS players_player_code_format;
ALTER TABLE players ADD CONSTRAINT players_player_code_format
  CHECK (player_code ~ '^[2-9A-HJKMNP-Z]{8}$');
CREATE UNIQUE INDEX IF NOT EXISTS players_player_code_idx
  ON players (player_code);


-- Friend network step 2: friend requests. Two accounts become friends when
-- one sends a request by the other's user code and the other accepts. Each
-- side then has exactly one player linked to the other: a player they chose
-- (so an existing player keeps their history) or a new one. Removing a
-- friend ends the connection and unlinks both sides; each host keeps their
-- games. Links and connections change only inside the functions below, which
-- derive the caller from the verified session, never from their arguments.
-- The runtime role has no direct access to the new tables.

-- The account a host's player stands for, once linked by an accepted request.
ALTER TABLE players
  ADD COLUMN IF NOT EXISTS linked_account_id uuid
  REFERENCES accounts(id) ON DELETE SET NULL;
ALTER TABLE players DROP CONSTRAINT IF EXISTS players_not_linked_to_owner;
ALTER TABLE players ADD CONSTRAINT players_not_linked_to_owner
  CHECK (
    linked_account_id IS NULL
    OR (owner_id IS NOT NULL AND linked_account_id <> owner_id)
  );
CREATE UNIQUE INDEX IF NOT EXISTS players_owner_linked_account_idx
  ON players (owner_id, linked_account_id)
  WHERE linked_account_id IS NOT NULL;

-- The runtime role may not set or change a link, and may not delete a linked
-- player: removing the friend comes first. The friend functions run as their
-- owner, so this guard doesn't apply to them, nor to the purge's cascades.
CREATE OR REPLACE FUNCTION public.guard_player_links()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF current_user <> 'menoka_app' THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF NEW.linked_account_id IS NOT NULL THEN
      RAISE EXCEPTION 'player links are set only by accepting a friend request';
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF NEW.linked_account_id IS DISTINCT FROM OLD.linked_account_id THEN
      RAISE EXCEPTION 'player links change only through friend requests';
    END IF;
    RETURN NEW;
  END IF;

  IF OLD.linked_account_id IS NOT NULL THEN
    RAISE EXCEPTION 'remove this friend before deleting their player';
  END IF;
  RETURN OLD;
END
$$;

DROP TRIGGER IF EXISTS players_guard_links ON players;
CREATE TRIGGER players_guard_links
  BEFORE INSERT OR UPDATE OR DELETE ON players
  FOR EACH ROW
  EXECUTE FUNCTION public.guard_player_links();

CREATE TABLE IF NOT EXISTS friend_requests (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  from_account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  to_account_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  status text NOT NULL DEFAULT 'pending' CHECK (
    status IN ('pending', 'accepted', 'declined', 'cancelled')
  ),
  -- The sender's own player for the recipient; NULL means a new player.
  from_player_id text REFERENCES players(id) ON DELETE SET NULL,
  -- The recipient's player code the sender says is theirs, if given. Only a
  -- hint for the recipient, who decides.
  claimed_player_code text CHECK (
    claimed_player_code IS NULL
    OR claimed_player_code ~ '^[2-9A-HJKMNP-Z]{8}$'
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  responded_at timestamptz,
  CONSTRAINT friend_requests_not_self CHECK (from_account_id <> to_account_id),
  CONSTRAINT friend_requests_response_time CHECK (
    (status = 'pending') = (responded_at IS NULL)
  )
);

-- At most one pending request between two people, in either direction.
CREATE UNIQUE INDEX IF NOT EXISTS friend_requests_one_pending_pair_idx
  ON friend_requests (
    LEAST(from_account_id, to_account_id),
    GREATEST(from_account_id, to_account_id)
  )
  WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS friend_requests_to_status_idx
  ON friend_requests (to_account_id, status);
CREATE INDEX IF NOT EXISTS friend_requests_from_status_idx
  ON friend_requests (from_account_id, status, responded_at);

CREATE TABLE IF NOT EXISTS friend_connections (
  account_low uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  account_high uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (account_low, account_high),
  CONSTRAINT friend_connections_ordered CHECK (account_low < account_high)
);
CREATE INDEX IF NOT EXISTS friend_connections_high_idx
  ON friend_connections (account_high);

-- Row security with no policy and no grants: the runtime role can't touch
-- either table except through the functions below.
ALTER TABLE friend_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE friend_connections ENABLE ROW LEVEL SECURITY;

-- The signed-in caller's account, which must be active. Every friend
-- function starts here. Not granted to the runtime role.
CREATE OR REPLACE FUNCTION public.friend_caller()
RETURNS uuid
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  caller uuid;
BEGIN
  SELECT account.id INTO caller
  FROM public.accounts AS account
  WHERE account.auth_user_id = public.current_app_auth_user_id()
    AND account.lifecycle_state = 'active';
  IF caller IS NULL THEN
    RAISE EXCEPTION 'friend:locked';
  END IF;
  RETURN caller;
END
$$;

-- How the caller stands with another account: connected, a pending request
-- either way, or none. Not granted to the runtime role.
CREATE OR REPLACE FUNCTION public.friend_relation(p_caller uuid, p_other uuid)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT CASE
    WHEN p_caller = p_other THEN 'self'
    WHEN EXISTS (
      SELECT 1 FROM public.friend_connections
      WHERE account_low = LEAST(p_caller, p_other)
        AND account_high = GREATEST(p_caller, p_other)
    ) THEN 'friends'
    WHEN EXISTS (
      SELECT 1 FROM public.friend_requests
      WHERE from_account_id = p_caller AND to_account_id = p_other
        AND status = 'pending'
    ) THEN 'request-sent'
    WHEN EXISTS (
      SELECT 1 FROM public.friend_requests
      WHERE from_account_id = p_other AND to_account_id = p_caller
        AND status = 'pending'
    ) THEN 'request-received'
    ELSE 'none'
  END
$$;

CREATE OR REPLACE FUNCTION public.friend_audit(
  p_owner uuid,
  p_action text,
  p_target_kind text,
  p_target_id text
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  INSERT INTO public.audit_events (owner_id, actor_auth_user_id, action, target_kind, target_id)
  VALUES (p_owner, public.current_app_auth_user_id(), p_action, p_target_kind, p_target_id)
$$;

-- Looks up an active account by exact user code. Returns only its display
-- name and how the caller stands with it; nothing when no active account has
-- that code.
CREATE OR REPLACE FUNCTION public.friend_find(p_code text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  caller uuid := public.friend_caller();
  target public.accounts%ROWTYPE;
BEGIN
  SELECT * INTO target
  FROM public.accounts
  WHERE user_code = p_code AND lifecycle_state = 'active';
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;
  RETURN jsonb_build_object(
    'displayName', target.display_name,
    'relation', public.friend_relation(caller, target.id)
  );
END
$$;

-- Sends a request to the account with this user code. p_my_player_id is the
-- caller's own player for that person (NULL for a new player);
-- p_claimed_player_code is the recipient's player code the caller says is
-- theirs (NULL when not given).
CREATE OR REPLACE FUNCTION public.friend_send(
  p_code text,
  p_my_player_id text,
  p_claimed_player_code text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  caller uuid := public.friend_caller();
  caller_name text;
  target public.accounts%ROWTYPE;
  relation text;
  request_id uuid;
BEGIN
  -- Serialises one person's sends, so the pending limit holds.
  SELECT display_name INTO caller_name
  FROM public.accounts WHERE id = caller FOR UPDATE;
  IF caller_name IS NULL THEN
    RAISE EXCEPTION 'friend:name-required';
  END IF;

  SELECT * INTO target
  FROM public.accounts
  WHERE user_code = p_code AND lifecycle_state = 'active';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'friend:not-found';
  END IF;

  relation := public.friend_relation(caller, target.id);
  IF relation = 'self' THEN RAISE EXCEPTION 'friend:self'; END IF;
  IF relation = 'friends' THEN RAISE EXCEPTION 'friend:already-friends'; END IF;
  IF relation = 'request-sent' THEN RAISE EXCEPTION 'friend:request-pending'; END IF;
  IF relation = 'request-received' THEN RAISE EXCEPTION 'friend:request-waiting'; END IF;

  IF EXISTS (
    SELECT 1 FROM public.friend_requests
    WHERE from_account_id = caller AND to_account_id = target.id
      AND status = 'declined'
      AND responded_at > now() - interval '7 days'
  ) THEN
    RAISE EXCEPTION 'friend:declined-recently';
  END IF;

  IF (
    SELECT count(*) FROM public.friend_requests
    WHERE from_account_id = caller AND status = 'pending'
  ) >= 20 THEN
    RAISE EXCEPTION 'friend:too-many-pending';
  END IF;

  IF p_my_player_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM public.players AS player
    WHERE player.id = p_my_player_id
      AND player.owner_id = caller
      AND player.deleted_at IS NULL
      AND player.linked_account_id IS NULL
      AND NOT EXISTS (
        SELECT 1 FROM public.friend_requests AS other
        WHERE other.from_account_id = caller
          AND other.status = 'pending'
          AND other.from_player_id = player.id
      )
  ) THEN
    RAISE EXCEPTION 'friend:player-unavailable';
  END IF;

  BEGIN
    INSERT INTO public.friend_requests (
      from_account_id, to_account_id, from_player_id, claimed_player_code
    )
    VALUES (caller, target.id, p_my_player_id, p_claimed_player_code)
    RETURNING id INTO request_id;
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION 'friend:request-pending';
  END;

  PERFORM public.friend_audit(caller, 'friend.request_sent', 'friend_request', request_id::text);
  RETURN jsonb_build_object('requestId', request_id, 'displayName', target.display_name);
END
$$;

-- Everything the caller's Friends card shows: friends, requests received and
-- requests sent. Accounts that are locked or being deleted are left out.
CREATE OR REPLACE FUNCTION public.friend_overview()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  caller uuid := public.friend_caller();
BEGIN
  RETURN jsonb_build_object(
    'friends', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'accountId', other.id,
          'displayName', other.display_name,
          'since', (extract(epoch FROM connection.created_at) * 1000)::bigint,
          'myPlayer', (
            SELECT jsonb_build_object('id', mine.id, 'name', mine.name)
            FROM public.players AS mine
            WHERE mine.owner_id = caller AND mine.linked_account_id = other.id
          ),
          'theirNameForMe', (
            SELECT theirs.name
            FROM public.players AS theirs
            WHERE theirs.owner_id = other.id AND theirs.linked_account_id = caller
          )
        )
        ORDER BY lower(other.display_name), other.id
      )
      FROM public.friend_connections AS connection
      JOIN public.accounts AS other
        ON other.id = CASE
          WHEN connection.account_low = caller THEN connection.account_high
          ELSE connection.account_low
        END
      WHERE caller IN (connection.account_low, connection.account_high)
        AND other.lifecycle_state = 'active'
    ), '[]'::jsonb),
    'received', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'requestId', request.id,
          'displayName', sender.display_name,
          'sentAt', (extract(epoch FROM request.created_at) * 1000)::bigint,
          'claimedPlayerCode', request.claimed_player_code,
          'claimedPlayer', (
            SELECT jsonb_build_object('id', claimed.id, 'name', claimed.name)
            FROM public.players AS claimed
            WHERE claimed.owner_id = caller
              AND claimed.player_code = request.claimed_player_code
              AND claimed.deleted_at IS NULL
              AND claimed.linked_account_id IS NULL
          )
        )
        ORDER BY request.created_at
      )
      FROM public.friend_requests AS request
      JOIN public.accounts AS sender ON sender.id = request.from_account_id
      WHERE request.to_account_id = caller
        AND request.status = 'pending'
        AND sender.lifecycle_state = 'active'
    ), '[]'::jsonb),
    'sent', COALESCE((
      SELECT jsonb_agg(
        jsonb_build_object(
          'requestId', request.id,
          'displayName', recipient.display_name,
          'sentAt', (extract(epoch FROM request.created_at) * 1000)::bigint,
          'myPlayerName', (
            SELECT mine.name FROM public.players AS mine
            WHERE mine.id = request.from_player_id AND mine.owner_id = caller
          )
        )
        ORDER BY request.created_at
      )
      FROM public.friend_requests AS request
      JOIN public.accounts AS recipient ON recipient.id = request.to_account_id
      WHERE request.from_account_id = caller
        AND request.status = 'pending'
    ), '[]'::jsonb)
  );
END
$$;

-- Accepts a request sent to the caller. The caller links the sender to one of
-- their own active, unlinked players (p_my_player_id), or adds a new player
-- (p_new_player_name, defaulting to the sender's name). On the sender's side,
-- the player the sender chose is linked if it is still free; otherwise a new
-- player is added under the caller's name, numbered if that name is taken.
CREATE OR REPLACE FUNCTION public.friend_accept(
  p_request_id uuid,
  p_my_player_id text,
  p_new_player_name text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  caller uuid := public.friend_caller();
  caller_name text;
  request public.friend_requests%ROWTYPE;
  sender public.accounts%ROWTYPE;
  new_name text;
  my_player text;
  their_player text;
  candidate text;
  suffix int := 1;
BEGIN
  SELECT display_name INTO caller_name FROM public.accounts WHERE id = caller;
  IF caller_name IS NULL THEN
    RAISE EXCEPTION 'friend:name-required';
  END IF;

  SELECT * INTO request
  FROM public.friend_requests
  WHERE id = p_request_id AND to_account_id = caller AND status = 'pending'
  FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'friend:request-not-found';
  END IF;

  SELECT * INTO sender
  FROM public.accounts
  WHERE id = request.from_account_id AND lifecycle_state = 'active';
  IF NOT FOUND OR sender.display_name IS NULL THEN
    RAISE EXCEPTION 'friend:request-not-found';
  END IF;

  -- The caller's side.
  IF p_my_player_id IS NOT NULL THEN
    UPDATE public.players
    SET linked_account_id = sender.id
    WHERE id = p_my_player_id
      AND owner_id = caller
      AND deleted_at IS NULL
      AND linked_account_id IS NULL
    RETURNING id INTO my_player;
    IF my_player IS NULL THEN
      RAISE EXCEPTION 'friend:player-unavailable';
    END IF;
  ELSE
    new_name := regexp_replace(btrim(COALESCE(p_new_player_name, '')), '\s+', ' ', 'g');
    IF new_name = '' THEN
      new_name := sender.display_name;
    END IF;
    IF char_length(new_name) > 80 THEN
      RAISE EXCEPTION 'friend:invalid-name';
    END IF;
    IF EXISTS (
      SELECT 1 FROM public.players
      WHERE owner_id = caller AND name_key = lower(new_name)
    ) THEN
      RAISE EXCEPTION 'friend:name-taken';
    END IF;
    INSERT INTO public.players (owner_id, name, name_key, linked_account_id)
    VALUES (caller, new_name, lower(new_name), sender.id)
    RETURNING id INTO my_player;
  END IF;

  -- The sender's side.
  IF request.from_player_id IS NOT NULL THEN
    UPDATE public.players
    SET linked_account_id = caller
    WHERE id = request.from_player_id
      AND owner_id = sender.id
      AND deleted_at IS NULL
      AND linked_account_id IS NULL
    RETURNING id INTO their_player;
  END IF;
  IF their_player IS NULL THEN
    candidate := caller_name;
    WHILE EXISTS (
      SELECT 1 FROM public.players
      WHERE owner_id = sender.id AND name_key = lower(candidate)
    ) LOOP
      suffix := suffix + 1;
      candidate := caller_name || ' (' || suffix || ')';
    END LOOP;
    INSERT INTO public.players (owner_id, name, name_key, linked_account_id)
    VALUES (sender.id, candidate, lower(candidate), caller)
    RETURNING id INTO their_player;
  END IF;

  INSERT INTO public.friend_connections (account_low, account_high)
  VALUES (LEAST(caller, sender.id), GREATEST(caller, sender.id));

  UPDATE public.friend_requests
  SET status = 'accepted', responded_at = now()
  WHERE id = request.id;

  PERFORM public.friend_audit(caller, 'friend.request_accepted', 'friend_request', request.id::text);
  PERFORM public.friend_audit(sender.id, 'friend.connected', 'friend_request', request.id::text);
  RETURN jsonb_build_object('myPlayerId', my_player, 'displayName', sender.display_name);
EXCEPTION
  WHEN unique_violation THEN
    RAISE EXCEPTION 'friend:already-friends';
END
$$;

CREATE OR REPLACE FUNCTION public.friend_decline(p_request_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  caller uuid := public.friend_caller();
BEGIN
  UPDATE public.friend_requests
  SET status = 'declined', responded_at = now()
  WHERE id = p_request_id AND to_account_id = caller AND status = 'pending';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'friend:request-not-found';
  END IF;
  PERFORM public.friend_audit(caller, 'friend.request_declined', 'friend_request', p_request_id::text);
END
$$;

CREATE OR REPLACE FUNCTION public.friend_cancel(p_request_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  caller uuid := public.friend_caller();
BEGIN
  UPDATE public.friend_requests
  SET status = 'cancelled', responded_at = now()
  WHERE id = p_request_id AND from_account_id = caller AND status = 'pending';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'friend:request-not-found';
  END IF;
  PERFORM public.friend_audit(caller, 'friend.request_cancelled', 'friend_request', p_request_id::text);
END
$$;

-- Ends a friendship and unlinks both sides' players. Works even while the
-- other account is locked for deletion.
CREATE OR REPLACE FUNCTION public.friend_remove(p_friend_account_id uuid)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  caller uuid := public.friend_caller();
BEGIN
  DELETE FROM public.friend_connections
  WHERE account_low = LEAST(caller, p_friend_account_id)
    AND account_high = GREATEST(caller, p_friend_account_id);
  IF NOT FOUND THEN
    RAISE EXCEPTION 'friend:not-friends';
  END IF;

  UPDATE public.players
  SET linked_account_id = NULL
  WHERE (owner_id = caller AND linked_account_id = p_friend_account_id)
     OR (owner_id = p_friend_account_id AND linked_account_id = caller);

  PERFORM public.friend_audit(caller, 'friend.removed', 'account', p_friend_account_id::text);
  PERFORM public.friend_audit(p_friend_account_id, 'friend.removed_by_friend', 'account', caller::text);
END
$$;

REVOKE ALL ON FUNCTION public.guard_player_links() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.friend_caller() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.friend_relation(uuid, uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.friend_audit(uuid, text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.friend_find(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.friend_send(text, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.friend_overview() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.friend_accept(uuid, text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.friend_decline(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.friend_cancel(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.friend_remove(uuid) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.friend_find(text) TO menoka_app;
GRANT EXECUTE ON FUNCTION public.friend_send(text, text, text) TO menoka_app;
GRANT EXECUTE ON FUNCTION public.friend_overview() TO menoka_app;
GRANT EXECUTE ON FUNCTION public.friend_accept(uuid, text, text) TO menoka_app;
GRANT EXECUTE ON FUNCTION public.friend_decline(uuid) TO menoka_app;
GRANT EXECUTE ON FUNCTION public.friend_cancel(uuid) TO menoka_app;
GRANT EXECUTE ON FUNCTION public.friend_remove(uuid) TO menoka_app;


-- Friend network step 3: group standings. A signed-in person sees the
-- standings of every host whose ledger has a player linked to them, while
-- the two are friends and both accounts are active. This function hands the
-- server those hosts' saved games; the server ranks them with the same code
-- the host's own standings use and sends only the ranked rows to the phone,
-- never the games themselves. Discarded games are left out, as they are from
-- the host's own standings.
CREATE OR REPLACE FUNCTION public.friend_group_sessions()
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  caller uuid := public.friend_caller();
BEGIN
  RETURN COALESCE((
    SELECT jsonb_agg(
      jsonb_build_object(
        'hostAccountId', host.id,
        'hostName', host.display_name,
        'myPlayerId', linked.id,
        'myPlayerName', linked.name,
        'sessions', COALESCE((
          SELECT jsonb_agg(
            jsonb_build_object(
              'id', session.id,
              'date', (extract(epoch FROM session.played_at) * 1000)::bigint,
              'startStack', session.starting_stack,
              'hands', session.hands,
              'results', normalized.results
            )
            ORDER BY session.played_at, session.created_at
          )
          FROM public.poker_sessions AS session
          JOIN LATERAL (
            SELECT jsonb_agg(
              jsonb_build_object(
                'playerId', result.player_id,
                'name', result.player_name,
                'net', result.net,
                'end', result.ending_stack,
                'buyIns', COALESCE(buy_ins.buy_ins, '[]'::jsonb)
              )
              ORDER BY result.position
            ) AS results
            FROM public.session_results AS result
            LEFT JOIN LATERAL (
              SELECT jsonb_agg(event.amount ORDER BY event.sequence) AS buy_ins
              FROM public.buy_in_events AS event
              WHERE event.owner_id = result.owner_id
                AND event.session_record_id = result.session_record_id
                AND event.player_id = result.player_id
            ) AS buy_ins ON true
            WHERE result.owner_id = session.owner_id
              AND result.session_record_id = session.record_id
              AND result.accounting_status IN ('verified', 'legacy_verified')
            HAVING count(*) > 0
          ) AS normalized ON true
          WHERE session.owner_id = host.id
            AND session.discarded_at IS NULL
        ), '[]'::jsonb)
      )
      ORDER BY lower(host.display_name), host.id
    )
    FROM public.players AS linked
    JOIN public.accounts AS host ON host.id = linked.owner_id
    WHERE linked.linked_account_id = caller
      AND host.lifecycle_state = 'active'
      AND EXISTS (
        SELECT 1 FROM public.friend_connections
        WHERE account_low = LEAST(caller, host.id)
          AND account_high = GREATEST(caller, host.id)
      )
  ), '[]'::jsonb);
END
$$;

REVOKE ALL ON FUNCTION public.friend_group_sessions() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.friend_group_sessions() TO menoka_app;
