CREATE TABLE IF NOT EXISTS app_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL UNIQUE,
  lifecycle_state text NOT NULL DEFAULT 'active' CHECK (
    lifecycle_state IN ('active', 'deletion_requested', 'purging')
  ),
  deletion_requested_at timestamptz,
  next_session_number bigint NOT NULL DEFAULT 1 CHECK (
    next_session_number > 0
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT accounts_deletion_state_consistent CHECK (
    (lifecycle_state = 'active' AND deletion_requested_at IS NULL)
    OR
    (lifecycle_state IN ('deletion_requested', 'purging') AND deletion_requested_at IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS players (
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
  name_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES accounts(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS players_owner_name_key_idx
  ON players (owner_id, name_key)
  WHERE owner_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS players_owner_active_name_idx
  ON players (owner_id, lower(name))
  WHERE owner_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS players_active_name_idx
  ON players (lower(name))
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS poker_sessions (
  record_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id text NOT NULL,
  session_number bigint GENERATED BY DEFAULT AS IDENTITY,
  game_name text CONSTRAINT poker_sessions_game_name_length CHECK (
    game_name IS NULL OR char_length(game_name) BETWEEN 1 AND 80
  ),
  played_at timestamptz NOT NULL,
  ended_at timestamptz NOT NULL,
  ante bigint NOT NULL CHECK (ante > 0),
  starting_stack bigint NOT NULL CHECK (starting_stack >= 0),
  hands integer NOT NULL CHECK (hands > 0),
  blind_history jsonb,
  results jsonb NOT NULL CHECK (
    jsonb_typeof(results) = 'array'
    AND jsonb_array_length(results) BETWEEN 2 AND 10
  ),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS session_number bigint
  GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS game_name text;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS blind_history jsonb;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS owner_session_number bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'poker_sessions_game_name_length'
      AND conrelid = 'public.poker_sessions'::regclass
  ) THEN
    ALTER TABLE poker_sessions
      ADD CONSTRAINT poker_sessions_game_name_length
      CHECK (
        game_name IS NULL OR char_length(game_name) BETWEEN 1 AND 80
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'poker_sessions_owner_number_pair'
      AND conrelid = 'public.poker_sessions'::regclass
  ) THEN
    ALTER TABLE poker_sessions
      ADD CONSTRAINT poker_sessions_owner_number_pair
      CHECK (
        (owner_id IS NULL AND owner_session_number IS NULL)
        OR
        (owner_id IS NOT NULL AND owner_session_number IS NOT NULL)
      );
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS poker_sessions_legacy_id_idx
  ON poker_sessions (id)
  WHERE owner_id IS NULL;

CREATE INDEX IF NOT EXISTS poker_sessions_played_at_idx
  ON poker_sessions (played_at DESC);

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS discarded_at timestamptz;

CREATE INDEX IF NOT EXISTS poker_sessions_active_played_at_idx
  ON poker_sessions (played_at DESC, created_at DESC)
  WHERE discarded_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS poker_sessions_owner_number_idx
  ON poker_sessions (owner_id, owner_session_number)
  WHERE owner_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS poker_sessions_owner_client_id_idx
  ON poker_sessions (owner_id, id)
  WHERE owner_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS poker_sessions_owner_played_at_idx
  ON poker_sessions (owner_id, played_at DESC, created_at DESC)
  WHERE owner_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS migration_mapping (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_kind text NOT NULL CHECK (source_kind IN ('player', 'session')),
  source_id text NOT NULL,
  target_owner_id uuid REFERENCES accounts(id) ON DELETE CASCADE,
  target_id text,
  review_status text NOT NULL DEFAULT 'pending' CHECK (
    review_status IN ('pending', 'approved', 'quarantined', 'migrated')
  ),
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (
    jsonb_typeof(provenance) = 'object'
  ),
  reviewed_at timestamptz,
  migrated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS migration_mapping_owner_source_idx
  ON migration_mapping (source_kind, source_id, target_owner_id)
  WHERE target_owner_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS audit_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  actor_auth_user_id uuid NOT NULL,
  action text NOT NULL CHECK (char_length(action) BETWEEN 1 AND 100),
  target_kind text NOT NULL CHECK (char_length(target_kind) BETWEEN 1 AND 60),
  target_id text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (
    jsonb_typeof(details) = 'object'
  ),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_events_owner_created_at_idx
  ON audit_events (owner_id, created_at DESC);

INSERT INTO players (name, name_key)
SELECT DISTINCT ON (name_key) name, name_key
FROM (
  SELECT
    btrim(result->>'name') AS name,
    lower(regexp_replace(btrim(result->>'name'), '\s+', ' ', 'g')) AS name_key
  FROM poker_sessions
  CROSS JOIN LATERAL jsonb_array_elements(results) AS result
  WHERE nullif(btrim(result->>'name'), '') IS NOT NULL
) AS existing_players
ORDER BY name_key, name
ON CONFLICT DO NOTHING;

UPDATE poker_sessions AS session
SET results = mapped.results
FROM (
  SELECT
    poker_sessions.record_id,
    jsonb_agg(
      result || jsonb_build_object('playerId', players.id)
      ORDER BY result_position
    ) AS results
  FROM poker_sessions
  CROSS JOIN LATERAL jsonb_array_elements(results)
    WITH ORDINALITY AS session_result(result, result_position)
  JOIN players
    ON players.name_key = lower(
      regexp_replace(btrim(result->>'name'), '\s+', ' ', 'g')
    )
  GROUP BY poker_sessions.record_id
) AS mapped
WHERE session.record_id = mapped.record_id
  AND session.results IS DISTINCT FROM mapped.results;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'players_owner_id_id_unique'
      AND conrelid = 'public.players'::regclass
  ) THEN
    ALTER TABLE players
      ADD CONSTRAINT players_owner_id_id_unique UNIQUE (owner_id, id);
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'poker_sessions_owner_record_unique'
      AND conrelid = 'public.poker_sessions'::regclass
  ) THEN
    ALTER TABLE poker_sessions
      ADD CONSTRAINT poker_sessions_owner_record_unique
      UNIQUE (owner_id, record_id);
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS session_results (
  owner_id uuid NOT NULL,
  session_record_id uuid NOT NULL,
  player_id text NOT NULL,
  position smallint NOT NULL CHECK (position BETWEEN 1 AND 10),
  player_name text NOT NULL CHECK (char_length(player_name) BETWEEN 1 AND 80),
  invested bigint NOT NULL CHECK (invested >= 0),
  ending_stack bigint NOT NULL CHECK (ending_stack >= 0),
  net bigint GENERATED ALWAYS AS (ending_stack - invested) STORED,
  accounting_status text NOT NULL CHECK (
    accounting_status IN ('verified', 'legacy_verified', 'unverified')
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_id, session_record_id, player_id),
  UNIQUE (owner_id, session_record_id, position),
  FOREIGN KEY (owner_id, session_record_id)
    REFERENCES poker_sessions (owner_id, record_id) ON DELETE CASCADE,
  FOREIGN KEY (owner_id, player_id)
    REFERENCES players (owner_id, id)
    ON DELETE NO ACTION DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE IF NOT EXISTS buy_in_events (
  owner_id uuid NOT NULL,
  session_record_id uuid NOT NULL,
  player_id text NOT NULL,
  sequence smallint NOT NULL CHECK (sequence BETWEEN 1 AND 64),
  kind text NOT NULL CHECK (kind IN ('initial', 'rebuy')),
  amount bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_id, session_record_id, player_id, sequence),
  FOREIGN KEY (owner_id, session_record_id, player_id)
    REFERENCES session_results (owner_id, session_record_id, player_id)
    ON DELETE CASCADE,
  CONSTRAINT buy_in_events_kind_sequence CHECK (
    (sequence = 1 AND kind = 'initial' AND amount >= 0)
    OR
    (sequence > 1 AND kind = 'rebuy' AND amount > 0)
  )
);

CREATE INDEX IF NOT EXISTS session_results_owner_player_idx
  ON session_results (owner_id, player_id, session_record_id);

CREATE INDEX IF NOT EXISTS buy_in_events_owner_session_idx
  ON buy_in_events (owner_id, session_record_id, player_id, sequence);

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM poker_sessions AS session
    CROSS JOIN LATERAL jsonb_array_elements(session.results) AS result(value)
    WHERE session.owner_id IS NOT NULL
      AND (
        nullif(result.value->>'playerId', '') IS NULL
        OR NOT EXISTS (
          SELECT 1
          FROM players AS player
          WHERE player.owner_id = session.owner_id
            AND player.id = result.value->>'playerId'
        )
        OR (
          result.value ? 'buyIns'
          AND CASE
            WHEN jsonb_typeof(result.value->'buyIns') <> 'array' THEN true
            ELSE jsonb_array_length(result.value->'buyIns') = 0
          END
        )
      )
  ) THEN
    RAISE EXCEPTION 'Owned session results have invalid player or buy-in references';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM (
      SELECT
        session.record_id,
        count(*) AS result_count,
        count(DISTINCT result.value->>'playerId') AS player_count,
        sum((result.value->>'end')::bigint) AS total_ending,
        sum((result.value->>'net')::bigint) AS total_net,
        sum(
          CASE
            WHEN result.value ? 'buyIns' THEN (
              SELECT sum(amount.value::bigint)
              FROM jsonb_array_elements_text(result.value->'buyIns')
                AS amount(value)
            )
            ELSE session.starting_stack
          END
        ) AS total_invested,
        bool_and(
          (result.value->>'end')::bigint - (result.value->>'net')::bigint
          = CASE
            WHEN result.value ? 'buyIns' THEN (
              SELECT sum(amount.value::bigint)
              FROM jsonb_array_elements_text(result.value->'buyIns')
                AS amount(value)
            )
            ELSE session.starting_stack
          END
        ) AS individual_balanced
      FROM poker_sessions AS session
      CROSS JOIN LATERAL jsonb_array_elements(session.results) AS result(value)
      WHERE session.owner_id IS NOT NULL
      GROUP BY session.record_id
    ) AS accounting
    WHERE accounting.result_count <> accounting.player_count
      OR NOT accounting.individual_balanced
      OR accounting.total_net <> 0
      OR accounting.total_ending <> accounting.total_invested
  ) THEN
    RAISE EXCEPTION 'Owned session accounting does not reconcile';
  END IF;
END
$$;

INSERT INTO session_results (
  owner_id,
  session_record_id,
  player_id,
  position,
  player_name,
  invested,
  ending_stack,
  accounting_status
)
SELECT
  session.owner_id,
  session.record_id,
  result.value->>'playerId',
  result.position,
  result.value->>'name',
  CASE
    WHEN result.value ? 'buyIns' THEN (
      SELECT sum(amount.value::bigint)
      FROM jsonb_array_elements_text(result.value->'buyIns') AS amount(value)
    )
    ELSE session.starting_stack
  END,
  (result.value->>'end')::bigint,
  'legacy_verified'
FROM poker_sessions AS session
CROSS JOIN LATERAL jsonb_array_elements(session.results)
  WITH ORDINALITY AS result(value, position)
WHERE session.owner_id IS NOT NULL
ON CONFLICT (owner_id, session_record_id, player_id) DO NOTHING;

INSERT INTO buy_in_events (
  owner_id,
  session_record_id,
  player_id,
  sequence,
  kind,
  amount
)
SELECT
  session.owner_id,
  session.record_id,
  result.value->>'playerId',
  buy_in.position,
  CASE WHEN buy_in.position = 1 THEN 'initial' ELSE 'rebuy' END,
  buy_in.value::bigint
FROM poker_sessions AS session
CROSS JOIN LATERAL jsonb_array_elements(session.results) AS result(value)
CROSS JOIN LATERAL jsonb_array_elements_text(
  CASE
    WHEN result.value ? 'buyIns' THEN result.value->'buyIns'
    ELSE jsonb_build_array(session.starting_stack)
  END
) WITH ORDINALITY AS buy_in(value, position)
WHERE session.owner_id IS NOT NULL
ON CONFLICT (owner_id, session_record_id, player_id, sequence) DO NOTHING;

CREATE OR REPLACE FUNCTION public.current_app_auth_user_id()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT CASE
    WHEN current_setting('app.current_auth_user_id', true)
      ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    THEN current_setting('app.current_auth_user_id', true)::uuid
    ELSE NULL
  END
$$;

CREATE OR REPLACE FUNCTION public.current_app_account_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT account.id
  FROM public.accounts AS account
  WHERE account.auth_user_id = public.current_app_auth_user_id()
$$;

REVOKE ALL ON FUNCTION public.current_app_auth_user_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.current_app_account_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_app_auth_user_id() TO menoka_app;
GRANT EXECUTE ON FUNCTION public.current_app_account_id() TO menoka_app;

ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE poker_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE session_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE buy_in_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE migration_mapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS accounts_runtime_isolation ON accounts;
CREATE POLICY accounts_runtime_isolation ON accounts
  FOR ALL TO menoka_app
  USING (auth_user_id = public.current_app_auth_user_id())
  WITH CHECK (auth_user_id = public.current_app_auth_user_id());

DROP POLICY IF EXISTS players_runtime_isolation ON players;
CREATE POLICY players_runtime_isolation ON players
  FOR ALL TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS poker_sessions_runtime_isolation ON poker_sessions;
CREATE POLICY poker_sessions_runtime_isolation ON poker_sessions
  FOR ALL TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS session_results_runtime_isolation ON session_results;
CREATE POLICY session_results_runtime_isolation ON session_results
  FOR ALL TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS buy_in_events_runtime_isolation ON buy_in_events;
CREATE POLICY buy_in_events_runtime_isolation ON buy_in_events
  FOR ALL TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS migration_mapping_runtime_isolation ON migration_mapping;
CREATE POLICY migration_mapping_runtime_isolation ON migration_mapping
  FOR SELECT TO menoka_app
  USING (target_owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS audit_events_runtime_isolation ON audit_events;
CREATE POLICY audit_events_runtime_isolation ON audit_events
  FOR SELECT TO menoka_app
  USING (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS audit_events_runtime_insert ON audit_events;
CREATE POLICY audit_events_runtime_insert ON audit_events
  FOR INSERT TO menoka_app
  WITH CHECK (
    owner_id = public.current_app_account_id()
    AND actor_auth_user_id = public.current_app_auth_user_id()
  );

REVOKE ALL ON SCHEMA public FROM menoka_app;
GRANT USAGE ON SCHEMA public TO menoka_app;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM menoka_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM menoka_app;
GRANT SELECT, INSERT, UPDATE ON accounts TO menoka_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON players TO menoka_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON poker_sessions TO menoka_app;
GRANT SELECT, INSERT ON session_results TO menoka_app;
GRANT SELECT, INSERT ON buy_in_events TO menoka_app;
GRANT SELECT, INSERT ON audit_events TO menoka_app;

-- The runtime role may only request deletion or cancel it inside the
-- 30-day grace period. Purging is reserved for the separate purge job.
CREATE OR REPLACE FUNCTION public.guard_account_lifecycle()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF current_user <> 'menoka_app' THEN
    RETURN NEW;
  END IF;

  IF NEW.lifecycle_state = OLD.lifecycle_state THEN
    IF NEW.deletion_requested_at IS DISTINCT FROM OLD.deletion_requested_at THEN
      RAISE EXCEPTION 'deletion time cannot change without a lifecycle change';
    END IF;
    RETURN NEW;
  END IF;

  IF OLD.lifecycle_state = 'active' AND NEW.lifecycle_state = 'deletion_requested' THEN
    NEW.deletion_requested_at := now();
    RETURN NEW;
  END IF;

  IF OLD.lifecycle_state = 'deletion_requested' AND NEW.lifecycle_state = 'active' THEN
    IF OLD.deletion_requested_at <= now() - interval '30 days' THEN
      RAISE EXCEPTION 'the recovery period has ended';
    END IF;
    NEW.deletion_requested_at := NULL;
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'account lifecycle change from % to % is not allowed',
    OLD.lifecycle_state, NEW.lifecycle_state;
END
$$;

DROP TRIGGER IF EXISTS accounts_guard_lifecycle ON accounts;
CREATE TRIGGER accounts_guard_lifecycle
  BEFORE UPDATE ON accounts
  FOR EACH ROW
  EXECUTE FUNCTION public.guard_account_lifecycle();
GRANT USAGE, SELECT ON SEQUENCE poker_sessions_session_number_seq
  TO menoka_app;

-- Account purge job. Requires the menoka_purge role (see migrations/README.md).
-- One row per purged account. It deliberately has no foreign key so it
-- outlives the account; the Auth user ID is cleared once the purge is done.
CREATE TABLE IF NOT EXISTS account_purges (
  account_id uuid PRIMARY KEY,
  auth_user_id uuid,
  deletion_requested_at timestamptz NOT NULL,
  claimed_at timestamptz NOT NULL DEFAULT now(),
  identity_deleted_at timestamptz,
  data_deleted_at timestamptz,
  completed_at timestamptz,
  attempts integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  last_error text CHECK (char_length(last_error) <= 500),
  last_attempt_at timestamptz,
  CONSTRAINT account_purges_completion_consistent CHECK (
    completed_at IS NULL
    OR (identity_deleted_at IS NOT NULL AND data_deleted_at IS NOT NULL AND auth_user_id IS NULL)
  )
);

ALTER TABLE account_purges ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON account_purges FROM PUBLIC;

-- Moves every account past its 30-day grace period to purging and returns
-- all unfinished purges, including ones a previous run could not finish.
CREATE OR REPLACE FUNCTION public.purge_claim_due_accounts(max_accounts integer)
RETURNS TABLE (account_id uuid, auth_user_id uuid, attempts integer)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  WITH due AS (
    UPDATE accounts AS account
    SET lifecycle_state = 'purging', updated_at = now()
    WHERE account.lifecycle_state = 'deletion_requested'
      AND account.deletion_requested_at <= now() - interval '30 days'
    RETURNING account.id, account.auth_user_id, account.deletion_requested_at
  )
  INSERT INTO account_purges (account_id, auth_user_id, deletion_requested_at)
  SELECT due.id, due.auth_user_id, due.deletion_requested_at FROM due
  ON CONFLICT ON CONSTRAINT account_purges_pkey DO NOTHING;

  RETURN QUERY
  SELECT purge.account_id, purge.auth_user_id, purge.attempts
  FROM account_purges AS purge
  WHERE purge.completed_at IS NULL
  ORDER BY purge.claimed_at
  LIMIT greatest(1, least(max_accounts, 100));
END
$$;

-- True while the Neon Auth user still exists, so the job can confirm a
-- deletion without relying on the provider's response code.
CREATE OR REPLACE FUNCTION public.purge_auth_identity_exists(target_auth_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM neon_auth."user" WHERE id = target_auth_user_id
  )
$$;

CREATE OR REPLACE FUNCTION public.purge_record_identity_deleted(target_account_id uuid)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  UPDATE account_purges
  SET identity_deleted_at = coalesce(identity_deleted_at, now())
  WHERE account_id = target_account_id AND completed_at IS NULL
$$;

-- Deletes the account and, through ON DELETE CASCADE, every row it owns.
-- Only accounts already claimed for purging whose identity is gone qualify.
CREATE OR REPLACE FUNCTION public.purge_delete_account_data(target_account_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  purge account_purges%ROWTYPE;
BEGIN
  SELECT * INTO purge FROM account_purges
  WHERE account_id = target_account_id AND completed_at IS NULL
  FOR UPDATE;
  IF NOT FOUND OR purge.identity_deleted_at IS NULL THEN
    RETURN false;
  END IF;

  DELETE FROM accounts
  WHERE id = target_account_id AND lifecycle_state = 'purging';

  UPDATE account_purges
  SET data_deleted_at = now(),
      completed_at = now(),
      auth_user_id = NULL,
      last_error = NULL,
      last_attempt_at = now(),
      attempts = attempts + 1
  WHERE account_id = target_account_id;
  RETURN true;
END
$$;

CREATE OR REPLACE FUNCTION public.purge_record_failure(target_account_id uuid, failure text)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  UPDATE account_purges
  SET attempts = attempts + 1,
      last_error = left(failure, 500),
      last_attempt_at = now()
  WHERE account_id = target_account_id AND completed_at IS NULL
$$;

REVOKE ALL ON FUNCTION public.purge_claim_due_accounts(integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.purge_auth_identity_exists(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.purge_record_identity_deleted(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.purge_delete_account_data(uuid) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.purge_record_failure(uuid, text) FROM PUBLIC;

GRANT USAGE ON SCHEMA public TO menoka_purge;
GRANT EXECUTE ON FUNCTION public.purge_claim_due_accounts(integer) TO menoka_purge;
GRANT EXECUTE ON FUNCTION public.purge_auth_identity_exists(uuid) TO menoka_purge;
GRANT EXECUTE ON FUNCTION public.purge_record_identity_deleted(uuid) TO menoka_purge;
GRANT EXECUTE ON FUNCTION public.purge_delete_account_data(uuid) TO menoka_purge;
GRANT EXECUTE ON FUNCTION public.purge_record_failure(uuid, text) TO menoka_purge;
