CREATE TABLE IF NOT EXISTS app_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS accounts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auth_user_id uuid NOT NULL UNIQUE,
  lifecycle_state text NOT NULL DEFAULT 'active' CHECK (
    lifecycle_state IN ('active', 'deletion_requested', 'purging')
  ),
  deletion_requested_at timestamptz,
  next_session_number bigint NOT NULL DEFAULT 1 CHECK (
    next_session_number > 0
  ),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT accounts_deletion_state_consistent CHECK (
    (lifecycle_state = 'active' AND deletion_requested_at IS NULL)
    OR
    (lifecycle_state IN ('deletion_requested', 'purging') AND deletion_requested_at IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS players (
  id text PRIMARY KEY DEFAULT gen_random_uuid()::text,
  name text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
  name_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

ALTER TABLE players
  ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES accounts(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS players_owner_name_key_idx
  ON players (owner_id, name_key)
  WHERE owner_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS players_owner_active_name_idx
  ON players (owner_id, lower(name))
  WHERE owner_id IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS players_active_name_idx
  ON players (lower(name))
  WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS poker_sessions (
  record_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  id text NOT NULL,
  session_number bigint GENERATED BY DEFAULT AS IDENTITY,
  game_name text CONSTRAINT poker_sessions_game_name_length CHECK (
    game_name IS NULL OR char_length(game_name) BETWEEN 1 AND 80
  ),
  played_at timestamptz NOT NULL,
  ended_at timestamptz NOT NULL,
  ante bigint NOT NULL CHECK (ante > 0),
  starting_stack bigint NOT NULL CHECK (starting_stack >= 0),
  hands integer NOT NULL CHECK (hands > 0),
  blind_history jsonb,
  results jsonb NOT NULL CHECK (
    jsonb_typeof(results) = 'array'
    AND jsonb_array_length(results) BETWEEN 2 AND 10
  ),
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS session_number bigint
  GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS game_name text;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS blind_history jsonb;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS owner_id uuid REFERENCES accounts(id) ON DELETE CASCADE;

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS owner_session_number bigint;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'poker_sessions_game_name_length'
      AND conrelid = 'public.poker_sessions'::regclass
  ) THEN
    ALTER TABLE poker_sessions
      ADD CONSTRAINT poker_sessions_game_name_length
      CHECK (
        game_name IS NULL OR char_length(game_name) BETWEEN 1 AND 80
      );
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'poker_sessions_owner_number_pair'
      AND conrelid = 'public.poker_sessions'::regclass
  ) THEN
    ALTER TABLE poker_sessions
      ADD CONSTRAINT poker_sessions_owner_number_pair
      CHECK (
        (owner_id IS NULL AND owner_session_number IS NULL)
        OR
        (owner_id IS NOT NULL AND owner_session_number IS NOT NULL)
      );
  END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS poker_sessions_legacy_id_idx
  ON poker_sessions (id)
  WHERE owner_id IS NULL;

CREATE INDEX IF NOT EXISTS poker_sessions_played_at_idx
  ON poker_sessions (played_at DESC);

ALTER TABLE poker_sessions
  ADD COLUMN IF NOT EXISTS discarded_at timestamptz;

CREATE INDEX IF NOT EXISTS poker_sessions_active_played_at_idx
  ON poker_sessions (played_at DESC, created_at DESC)
  WHERE discarded_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS poker_sessions_owner_number_idx
  ON poker_sessions (owner_id, owner_session_number)
  WHERE owner_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS poker_sessions_owner_client_id_idx
  ON poker_sessions (owner_id, id)
  WHERE owner_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS poker_sessions_owner_played_at_idx
  ON poker_sessions (owner_id, played_at DESC, created_at DESC)
  WHERE owner_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS migration_mapping (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  source_kind text NOT NULL CHECK (source_kind IN ('player', 'session')),
  source_id text NOT NULL,
  target_owner_id uuid REFERENCES accounts(id) ON DELETE CASCADE,
  target_id text,
  review_status text NOT NULL DEFAULT 'pending' CHECK (
    review_status IN ('pending', 'approved', 'quarantined', 'migrated')
  ),
  provenance jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (
    jsonb_typeof(provenance) = 'object'
  ),
  reviewed_at timestamptz,
  migrated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS migration_mapping_owner_source_idx
  ON migration_mapping (source_kind, source_id, target_owner_id)
  WHERE target_owner_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS audit_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
  actor_auth_user_id uuid NOT NULL,
  action text NOT NULL CHECK (char_length(action) BETWEEN 1 AND 100),
  target_kind text NOT NULL CHECK (char_length(target_kind) BETWEEN 1 AND 60),
  target_id text,
  details jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (
    jsonb_typeof(details) = 'object'
  ),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS audit_events_owner_created_at_idx
  ON audit_events (owner_id, created_at DESC);

INSERT INTO players (name, name_key)
SELECT DISTINCT ON (name_key) name, name_key
FROM (
  SELECT
    btrim(result->>'name') AS name,
    lower(regexp_replace(btrim(result->>'name'), '\s+', ' ', 'g')) AS name_key
  FROM poker_sessions
  CROSS JOIN LATERAL jsonb_array_elements(results) AS result
  WHERE nullif(btrim(result->>'name'), '') IS NOT NULL
) AS existing_players
ORDER BY name_key, name
ON CONFLICT DO NOTHING;

UPDATE poker_sessions AS session
SET results = mapped.results
FROM (
  SELECT
    poker_sessions.record_id,
    jsonb_agg(
      result || jsonb_build_object('playerId', players.id)
      ORDER BY result_position
    ) AS results
  FROM poker_sessions
  CROSS JOIN LATERAL jsonb_array_elements(results)
    WITH ORDINALITY AS session_result(result, result_position)
  JOIN players
    ON players.name_key = lower(
      regexp_replace(btrim(result->>'name'), '\s+', ' ', 'g')
    )
  GROUP BY poker_sessions.record_id
) AS mapped
WHERE session.record_id = mapped.record_id
  AND session.results IS DISTINCT FROM mapped.results;

CREATE OR REPLACE FUNCTION public.current_app_auth_user_id()
RETURNS uuid
LANGUAGE sql
STABLE
AS $$
  SELECT CASE
    WHEN current_setting('app.current_auth_user_id', true)
      ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
    THEN current_setting('app.current_auth_user_id', true)::uuid
    ELSE NULL
  END
$$;

CREATE OR REPLACE FUNCTION public.current_app_account_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT account.id
  FROM public.accounts AS account
  WHERE account.auth_user_id = public.current_app_auth_user_id()
$$;

REVOKE ALL ON FUNCTION public.current_app_auth_user_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.current_app_account_id() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.current_app_auth_user_id() TO menoka_app;
GRANT EXECUTE ON FUNCTION public.current_app_account_id() TO menoka_app;

ALTER TABLE accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE players ENABLE ROW LEVEL SECURITY;
ALTER TABLE poker_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE migration_mapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS accounts_runtime_isolation ON accounts;
CREATE POLICY accounts_runtime_isolation ON accounts
  FOR ALL TO menoka_app
  USING (auth_user_id = public.current_app_auth_user_id())
  WITH CHECK (auth_user_id = public.current_app_auth_user_id());

DROP POLICY IF EXISTS players_runtime_isolation ON players;
CREATE POLICY players_runtime_isolation ON players
  FOR ALL TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS poker_sessions_runtime_isolation ON poker_sessions;
CREATE POLICY poker_sessions_runtime_isolation ON poker_sessions
  FOR ALL TO menoka_app
  USING (owner_id = public.current_app_account_id())
  WITH CHECK (owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS migration_mapping_runtime_isolation ON migration_mapping;
CREATE POLICY migration_mapping_runtime_isolation ON migration_mapping
  FOR SELECT TO menoka_app
  USING (target_owner_id = public.current_app_account_id());

DROP POLICY IF EXISTS audit_events_runtime_isolation ON audit_events;
CREATE POLICY audit_events_runtime_isolation ON audit_events
  FOR SELECT TO menoka_app
  USING (owner_id = public.current_app_account_id());

REVOKE ALL ON SCHEMA public FROM menoka_app;
GRANT USAGE ON SCHEMA public TO menoka_app;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM menoka_app;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM menoka_app;
GRANT SELECT, INSERT, UPDATE ON accounts TO menoka_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON players TO menoka_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON poker_sessions TO menoka_app;
GRANT USAGE, SELECT ON SEQUENCE poker_sessions_session_number_seq
  TO menoka_app;
